server:
  port: 8001
  
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8000/eureka/

management:
 tracing:
  sampling:
   probability: 1.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices  # JDBC URL for connecting to your MySQL instance
    username: root  # Database username
    password: manager  # Database password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class
    hikari:
      connection-test-query: SELECT 1  # Optional: Test query to validate the connection
      maximum-pool-size: 5  # Optional: Maximum number of connections in the pool
  jpa:
    hibernate:
      ddl-auto: update  # Hibernate DDL mode (create, update, none, ...)
    show-sql: true  # Enable SQL logging for debugging

 